version: '3.8'

services:
  users_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile
    volumes:
      - ./users_service:/app/users_service
    environment:
      - APP_ENV=dev
    depends_on:
      - rabbitmq

  notifications_service:
    build:
      context: ./notifications_service
      dockerfile: Dockerfile
    volumes:
      - ./notifications_service:/var/www/notifications_service
    environment:
      - APP_ENV=dev
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=secret
